# Configuration des APIs
google.api.key=AIzaSyBATEdy1lIgd0Jv8b_l6Wu9o-BYiarWHGI

# Database Configuration
database.url=jdbc:mysql://localhost:3306/mindaudit
database.user=root
database.password=

# Application Info
app.name=MindAudit
app.version=1.0.0
app.description=Système de Gestion d'Audit Interne

# Email Configuration (SMTP Gmail)
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.username=eleammar21@gmail.com
mail.password=YOUR_SMTP_APP_PASSWORD
mail.admin.target=eleammar21@gmail.com
